---
name: "Scheduled Release"

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  generate-build-matrix:
    name: Generate matrix for building images
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.fetch.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Generate Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: "${{ secrets.HOMEOPS_BOT_APP_ID }}"
          private_key: "${{ secrets.HOMEOPS_BOT_PRIVATE_KEY }}"

      - name: Fetch new app versions
        id: fetch
        run: ./.github/scripts/fetch.sh
        env:
          TOKEN: "${{ steps.generate-token.outputs.token }}"

  images-build:
    uses: ahinko/container-images/.github/workflows/action-image-build.yaml@main
    if: needs.generate-build-matrix.outputs.matrix != '[]'
    needs: ["generate-build-matrix"]
    with:
      imagesToBuild: "${{ needs.generate-build-matrix.outputs.matrix }}"
      pushImages: "true"
      updateMetadata: "true"
    secrets: inherit
